In [3]:
import numpy as np
from sklearn.datasets import load_diabetes

In [4]:
X,y = load_diabetes(return_X_y=True)

In [5]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [6]:
X.shape

(442, 10)

In [7]:
y.shape

(442,)

In [8]:
from sklearn.model_selection import train_test_split

In [14]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [15]:
X_train.shape,y_train.shape

((353, 10), (353,))

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
lr = LinearRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)

In [18]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.4526027629719196

In [19]:
lr.coef_

array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
       -931.48884588,  518.06227698,  163.41998299,  275.31790158,
        736.1988589 ,   48.67065743])

In [20]:
lr.intercept_

151.34560453985995

# Custom Class

In [30]:
class MYLinearRegression:
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None
    def fit(self,X_train,y_train):
        X_train = np.insert(X_train,0,1,axis=1)

        # calcuate the coefficients
        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]

    def predict(self,X_test):
        return X_test.dot(self.coef_) + self.intercept_

In [34]:
mylr = MYLinearRegression()

In [35]:
mylr.fit(X_train,y_train)

In [36]:
y_pred = mylr.predict(X_test)

In [38]:
r2_score(y_test,y_pred)

0.45260276297191904

In [39]:
mylr.intercept_

151.34560453986

In [40]:
mylr.coef_

array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
       -931.48884588,  518.06227698,  163.41998299,  275.31790158,
        736.1988589 ,   48.67065743])